deployment:
  tasks:
    - export DEPLOYPATH=/home/azwywnto/repositories/shopify-section-app-final
    - cd $DEPLOYPATH && npm install --production=false
    - cd $DEPLOYPATH && npx prisma generate
    - cd $DEPLOYPATH && npm run build
